spring.application.name=demoSpring

server.port=8080

# niveau de level logging
logging.level.root=error
# main package
logging.level.fr.juliuselgringo=info
# jdbc
logging.level.org.springframework.data=info
logging.level.springframework.jdbc.core.JdbcTemplate=DEBUG
# tomcat
logging.level.org.springframework.boot.web.embeded.tomcat=info

# parametrage de la BDD
spring.datasource.url=jdbc:mysql://localhost:3306/gestbook
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# modifie la BDD en fonction des entity pour le mode developpement sinon none
spring.jpa.hibernate.ddl-auto=update
